//! Sync command implementation for generating files from CUE configuration.
//!
//! Supports generating:
//! - Ignore files (.gitignore, .dockerignore, etc.) from the `ignore` field
//! - CODEOWNERS file from the `owners` field
//! - Project files from CUE cube templates

use super::owners;
use cuengine::CueEvaluator;
use cuenv_core::Result;
use cuenv_core::manifest::Cuenv;
use cuenv_ignore::{FileStatus, IgnoreFile, IgnoreFiles};
use std::path::{Path, PathBuf};
use tracing::instrument;

/// The header added to all cuenv-generated ignore files.
const CUENV_IGNORE_HEADER: &str = "Generated by cuenv - do not edit\nSource: env.cue";

/// Convert manifest ignore configuration to `cuenv_ignore::IgnoreFile` configs.
fn convert_to_ignore_files(manifest: &Cuenv) -> Vec<IgnoreFile> {
    let Some(ignore) = &manifest.ignore else {
        return Vec::new();
    };

    ignore
        .iter()
        .map(|(tool, value)| {
            IgnoreFile::new(tool)
                .patterns(value.patterns().iter().cloned())
                .filename_opt(value.filename())
                .header(CUENV_IGNORE_HEADER)
        })
        .collect()
}

/// Execute the sync ignore command.
///
/// Reads the CUE configuration and generates ignore files based on the `ignore` field.
#[instrument(name = "sync_ignore")]
pub async fn execute_sync_ignore(
    path: &str,
    package: &str,
    dry_run: bool,
    check: bool,
) -> Result<String> {
    tracing::info!("Starting sync ignore command");

    // Create CUE evaluator
    let evaluator = CueEvaluator::builder()
        .build()
        .map_err(super::convert_engine_error)?;

    // Convert path string to Path
    let dir_path = Path::new(path);

    // Evaluate the CUE package
    tracing::debug!("Evaluating CUE package '{}' at path '{}'", package, path);
    let manifest: Cuenv = evaluator
        .evaluate_typed(dir_path, package)
        .map_err(super::convert_engine_error)?;

    // Convert to ignore files
    let files = convert_to_ignore_files(&manifest);

    if files.is_empty() {
        tracing::info!("No ignore patterns configured");
        return Ok(
            "No ignore patterns configured. Add an `ignore` field to your env.cue.".to_string(),
        );
    }

    // Check if all files have empty patterns
    let all_empty = files.iter().all(|f| f.patterns_list().is_empty());
    if all_empty {
        return Ok("No ignore files to generate (all pattern lists are empty).".to_string());
    }

    // In check mode, use dry_run and verify files match
    let effective_dry_run = dry_run || check;

    // Generate ignore files using the cuenv-ignore crate
    let result = IgnoreFiles::builder()
        .directory(dir_path)
        .require_git_repo(true)
        .dry_run(effective_dry_run)
        .files(files)
        .generate()
        .map_err(|e| match e {
            cuenv_ignore::Error::NotInGitRepo => {
                cuenv_core::Error::configuration("cuenv sync must be run within a Git repository")
            }
            cuenv_ignore::Error::BareRepository => {
                cuenv_core::Error::configuration("Cannot sync in a bare Git repository")
            }
            cuenv_ignore::Error::OutsideGitRepo => cuenv_core::Error::configuration(
                "Target directory must be within the Git repository",
            ),
            cuenv_ignore::Error::InvalidToolName { name, reason } => {
                cuenv_core::Error::configuration(format!("Invalid tool name '{name}': {reason}"))
            }
            cuenv_ignore::Error::Io(io_err) => cuenv_core::Error::Io {
                source: io_err,
                path: Some(dir_path.to_path_buf().into_boxed_path()),
                operation: "sync ignore files".to_string(),
            },
        })?;

    // In check mode, verify all files are unchanged
    if check {
        let mut out_of_sync = Vec::new();
        for file in &result.files {
            match file.status {
                FileStatus::WouldCreate | FileStatus::WouldUpdate => {
                    out_of_sync.push(file.filename.clone());
                }
                FileStatus::Unchanged | FileStatus::Created | FileStatus::Updated => {}
            }
        }
        if !out_of_sync.is_empty() {
            return Err(cuenv_core::Error::configuration(format!(
                "Ignore files out of sync: {}. Run 'cuenv sync ignore' to update.",
                out_of_sync.join(", ")
            )));
        }
        return Ok("Ignore files are in sync.".to_string());
    }

    // Format output
    let mut output_lines = Vec::new();

    for file in &result.files {
        let status_str = match file.status {
            FileStatus::Created => format!(
                "Created {} ({} patterns)",
                file.filename, file.pattern_count
            ),
            FileStatus::Updated => format!(
                "Updated {} ({} patterns)",
                file.filename, file.pattern_count
            ),
            FileStatus::Unchanged => format!("Unchanged {}", file.filename),
            FileStatus::WouldCreate => format!(
                "Would create {} ({} patterns)",
                file.filename, file.pattern_count
            ),
            FileStatus::WouldUpdate => format!(
                "Would update {} ({} patterns)",
                file.filename, file.pattern_count
            ),
        };
        output_lines.push(status_str);
    }

    if output_lines.is_empty() {
        return Ok("No ignore files to generate (all pattern lists are empty).".to_string());
    }

    let output = output_lines.join("\n");
    tracing::info!("Sync ignore command completed successfully");
    Ok(output)
}

/// Execute the sync codeowners command.
///
/// Reads the CUE configuration and generates CODEOWNERS file based on the `owners` field.
/// When `allow_missing_config` is true, missing owners config will return a message instead of error.
#[instrument(name = "sync_codeowners")]
pub async fn execute_sync_codeowners(
    path: &str,
    package: &str,
    dry_run: bool,
    check: bool,
) -> Result<String> {
    execute_sync_codeowners_inner(path, package, dry_run, check, false).await
}

/// Execute the sync codeowners command with option to allow missing config.
pub async fn execute_sync_codeowners_optional(
    path: &str,
    package: &str,
    dry_run: bool,
    check: bool,
) -> Result<String> {
    execute_sync_codeowners_inner(path, package, dry_run, check, true).await
}

/// Inner implementation that handles the `allow_missing_config` flag.
async fn execute_sync_codeowners_inner(
    path: &str,
    package: &str,
    dry_run: bool,
    check: bool,
    allow_missing_config: bool,
) -> Result<String> {
    tracing::info!("Starting sync codeowners command");

    let result = if check {
        owners::execute_owners_check(path, package).await
    } else {
        owners::execute_owners_sync(path, package, dry_run).await
    };

    // When called from aggregate sync (allow_missing_config=true), treat missing config as no-op
    match result {
        Ok(output) => Ok(output),
        Err(cuenv_core::Error::Configuration { message, .. })
            if allow_missing_config && message.contains("No 'owners' configuration") =>
        {
            Ok("No owners configuration found. Add an 'owners' section to your env.cue to enable CODEOWNERS sync.".to_string())
        }
        Err(cuenv_core::Error::Configuration { message, .. })
            if allow_missing_config
                && message.contains("No code ownership rules defined") =>
        {
            Ok("No code ownership rules defined.".to_string())
        }
        Err(e) => Err(e),
    }
}

/// Execute the sync cubes command.
///
/// Syncs cube-generated files for projects in the CUE module.
/// When `local_only` is true (path is "."), only syncs the current project.
/// Otherwise, discovers and syncs all projects with cube configurations.
#[instrument(name = "sync_cubes")]
pub async fn execute_sync_cubes(
    path: &str,
    package: &str,
    dry_run: bool,
    check: bool,
    diff: bool,
) -> Result<String> {
    let _ = diff; // TODO: implement diff mode
    tracing::info!("Starting sync cubes command");

    let dir_path = Path::new(path);

    // Check if we're running locally (path is ".")
    let local_only = path == ".";

    if local_only {
        // Local mode: sync only the current project
        return execute_sync_cubes_local(dir_path, package, dry_run, check);
    }

    // Module mode: discover all projects and sync their cubes
    execute_sync_cubes_all(dir_path, package, dry_run, check)
}

/// Sync cubes for the local project only
fn execute_sync_cubes_local(
    dir_path: &Path,
    package: &str,
    dry_run: bool,
    check: bool,
) -> Result<String> {
    // Auto-detect package name from env.cue if using default
    let effective_package = if package == "cuenv" {
        detect_package_name(dir_path)?
    } else {
        package.to_string()
    };

    let evaluator = CueEvaluator::builder()
        .build()
        .map_err(super::convert_engine_error)?;

    let manifest: Cuenv = evaluator
        .evaluate_typed(dir_path, &effective_package)
        .map_err(super::convert_engine_error)?;

    let Some(cube_config) = &manifest.cube else {
        return Ok("No cube configuration found in this project.".to_string());
    };

    sync_cube_files(dir_path, &manifest.name, cube_config, dry_run, check)
}

/// Discover all projects and sync their cubes
fn execute_sync_cubes_all(
    dir_path: &Path,
    _package: &str,
    dry_run: bool,
    check: bool,
) -> Result<String> {
    use cuenv_core::tasks::discovery::TaskDiscovery;

    // Find the CUE module root
    let module_root = find_cue_module_root(dir_path).ok_or_else(|| {
        cuenv_core::Error::configuration("Not in a CUE module (no cue.mod found)")
    })?;

    // Create evaluator for discovery
    let evaluator = CueEvaluator::builder()
        .build()
        .map_err(super::convert_engine_error)?;

    // Evaluation function for discovery
    let eval_fn: cuenv_core::tasks::discovery::EvalFn = Box::new(move |project_path: &Path| {
        let pkg = detect_package_name(project_path).map_err(|e| e.to_string())?;
        evaluator
            .evaluate_typed(project_path, &pkg)
            .map_err(|e| e.to_string())
    });

    let mut discovery = TaskDiscovery::new(module_root.clone()).with_eval_fn(eval_fn);
    discovery.discover().map_err(|e| {
        cuenv_core::Error::configuration(format!("Failed to discover projects: {e}"))
    })?;

    let mut output_lines = Vec::new();
    let mut total_files = 0;

    for project in discovery.projects() {
        let Some(cube_config) = &project.manifest.cube else {
            continue; // Skip projects without cube config
        };

        let project_output = sync_cube_files(
            &project.project_root,
            &project.manifest.name,
            cube_config,
            dry_run,
            check,
        )?;

        if !project_output.is_empty() {
            output_lines.push(format!("Project: {}", project.manifest.name));
            output_lines.push(project_output);
            total_files += cube_config.files.len();
        }
    }

    if output_lines.is_empty() {
        return Ok("No projects with cube configurations found.".to_string());
    }

    if dry_run {
        output_lines.insert(0, format!("Would generate {total_files} files:"));
    } else if check {
        output_lines.insert(0, format!("Checked {total_files} files:"));
    }

    Ok(output_lines.join("\n"))
}

/// Sync cube files for a single project
fn sync_cube_files(
    project_root: &Path,
    project_name: &str,
    cube_config: &cuenv_core::manifest::CubeConfig,
    dry_run: bool,
    check: bool,
) -> Result<String> {
    use cuenv_core::manifest::FileMode;

    let mut output_lines = Vec::new();

    for (file_path, file_def) in &cube_config.files {
        let output_path = project_root.join(file_path);

        match file_def.mode {
            FileMode::Managed => {
                if check {
                    // Check if file exists and matches
                    if output_path.exists() {
                        let existing = std::fs::read_to_string(&output_path).unwrap_or_default();
                        if existing == file_def.content {
                            output_lines.push(format!("  OK: {file_path}"));
                        } else {
                            output_lines.push(format!("  Out of sync: {file_path}"));
                        }
                    } else {
                        output_lines.push(format!("  Missing: {file_path}"));
                    }
                } else if dry_run {
                    if output_path.exists() {
                        output_lines.push(format!("  Would update: {file_path}"));
                    } else {
                        output_lines.push(format!("  Would create: {file_path}"));
                    }
                } else {
                    // Actually write the file
                    if let Some(parent) = output_path.parent() {
                        std::fs::create_dir_all(parent)?;
                    }
                    std::fs::write(&output_path, &file_def.content)?;
                    output_lines.push(format!("  Generated: {file_path}"));
                }
            }
            FileMode::Scaffold => {
                if output_path.exists() {
                    if !dry_run && !check {
                        tracing::debug!("Skipping {} (scaffold mode, file exists)", file_path);
                    }
                    output_lines.push(format!("  Skipped (exists): {file_path}"));
                } else if check {
                    output_lines.push(format!("  Missing scaffold: {file_path}"));
                } else if dry_run {
                    output_lines.push(format!("  Would scaffold: {file_path}"));
                } else {
                    // Actually write the file
                    if let Some(parent) = output_path.parent() {
                        std::fs::create_dir_all(parent)?;
                    }
                    std::fs::write(&output_path, &file_def.content)?;
                    output_lines.push(format!("  Scaffolded: {file_path}"));
                }
            }
        }
    }

    tracing::info!(
        project = project_name,
        files = cube_config.files.len(),
        "Cube sync complete"
    );

    Ok(output_lines.join("\n"))
}

/// Find the CUE module root by walking up directories looking for cue.mod
fn find_cue_module_root(start: &Path) -> Option<PathBuf> {
    let mut current = start.to_path_buf();
    loop {
        if current.join("cue.mod").exists() {
            return Some(current);
        }
        if !current.pop() {
            return None;
        }
    }
}

/// Detect the CUE package name from env.cue
fn detect_package_name(project_path: &Path) -> Result<String> {
    let env_cue = project_path.join("env.cue");
    if !env_cue.exists() {
        return Ok("cuenv".to_string());
    }

    let content = std::fs::read_to_string(&env_cue)?;
    for line in content.lines().take(10) {
        let trimmed = line.trim();
        if trimmed.starts_with("package ") {
            return Ok(trimmed
                .strip_prefix("package ")
                .unwrap_or("cuenv")
                .trim()
                .to_string());
        }
    }

    Ok("cuenv".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use cuenv_core::manifest::{IgnoreEntry, IgnoreValue};
    use std::collections::HashMap;

    #[test]
    fn test_convert_to_ignore_files_empty() {
        let manifest = Cuenv::new("test");
        let files = convert_to_ignore_files(&manifest);
        assert!(files.is_empty());
    }

    #[test]
    fn test_convert_to_ignore_files_simple_patterns() {
        let mut manifest = Cuenv::new("test");
        let mut ignore = HashMap::new();
        ignore.insert(
            "git".to_string(),
            IgnoreValue::Patterns(vec!["node_modules/".to_string(), ".env".to_string()]),
        );
        manifest.ignore = Some(ignore);

        let files = convert_to_ignore_files(&manifest);
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].tool(), "git");
        assert_eq!(files[0].patterns_list(), &["node_modules/", ".env"]);
        assert_eq!(files[0].output_filename(), ".gitignore");
    }

    #[test]
    fn test_convert_to_ignore_files_extended_with_filename() {
        let mut manifest = Cuenv::new("test");
        let mut ignore = HashMap::new();
        ignore.insert(
            "custom".to_string(),
            IgnoreValue::Extended(IgnoreEntry {
                patterns: vec!["*.tmp".to_string()],
                filename: Some(".myignore".to_string()),
            }),
        );
        manifest.ignore = Some(ignore);

        let files = convert_to_ignore_files(&manifest);
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].tool(), "custom");
        assert_eq!(files[0].patterns_list(), &["*.tmp"]);
        assert_eq!(files[0].output_filename(), ".myignore");
    }

    #[test]
    fn test_convert_to_ignore_files_has_cuenv_header() {
        let mut manifest = Cuenv::new("test");
        let mut ignore = HashMap::new();
        ignore.insert(
            "git".to_string(),
            IgnoreValue::Patterns(vec!["*.log".to_string()]),
        );
        manifest.ignore = Some(ignore);

        let files = convert_to_ignore_files(&manifest);
        let content = files[0].generate();

        assert!(content.contains("# Generated by cuenv"));
        assert!(content.contains("# Source: env.cue"));
    }
}
