# Buildkite bootstrap pipeline for cuenv
# This generates a dynamic pipeline based on affected tasks
env:
  USER: root

steps:
  - label: ":pipeline: Generate Pipeline"
    command: |
      curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux --no-confirm --init none
      . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use cuenv
      nix build .#cuenv --accept-flake-config
      ./result/bin/cuenv ci --format buildkite | buildkite-agent pipeline upload
