# Buildkite bootstrap pipeline for cuenv
# This generates a dynamic pipeline based on affected tasks
steps:
  - label: ":pipeline: Generate Pipeline"
    command: |
      nix build .#cuenv
      ./result/bin/cuenv ci --format buildkite | buildkite-agent pipeline upload
