use crate::core::types::PackageManager;
use crate::error::{Error, Result};
use std::fs;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};

/// Scans the root directory for package manager lockfiles.
///
/// Returns a list of tuples containing the detected package manager and the
/// path to its lockfile.
pub(super) fn find_lockfiles(root: &Path) -> Vec<(PackageManager, PathBuf)> {
    let mut lockfiles = Vec::new();

    let candidates = [
        PackageManager::Npm,
        PackageManager::Bun,
        PackageManager::Pnpm,
        PackageManager::YarnClassic,
        PackageManager::Cargo,
        PackageManager::Deno,
    ];

    for manager in candidates {
        let lockfile_path = root.join(manager.lockfile_name());
        if lockfile_path.exists() {
            lockfiles.push((manager, lockfile_path));
        }
    }

    lockfiles
}

/// Validates that a workspace configuration file exists and is parseable.
///
/// Returns `Ok(true)` if the config is valid, `Ok(false)` if it doesn't exist,
/// or `Err` if it exists but is invalid.
pub(super) fn validate_workspace_config(root: &Path, manager: PackageManager) -> Result<bool> {
    let config_path = root.join(manager.workspace_config_name());

    if !config_path.exists() {
        return Ok(false);
    }

    let content = fs::read_to_string(&config_path).map_err(|e| Error::Io {
        source: e,
        path: Some(config_path.clone()),
        operation: "reading workspace config".to_string(),
    })?;

    match manager {
        PackageManager::Npm
        | PackageManager::Bun
        | PackageManager::YarnClassic
        | PackageManager::YarnModern
        | PackageManager::Deno => {
            serde_json::from_str::<serde_json::Value>(&content).map_err(|e| {
                Error::InvalidWorkspaceConfig {
                    path: config_path,
                    message: format!("Invalid JSON: {e}"),
                }
            })?;
            Ok(true)
        }
        PackageManager::Cargo => {
            toml::from_str::<toml::Value>(&content).map_err(|e| Error::InvalidWorkspaceConfig {
                path: config_path,
                message: format!("Invalid TOML: {e}"),
            })?;
            Ok(true)
        }
        PackageManager::Pnpm => {
            serde_yaml::from_str::<serde_yaml::Value>(&content).map_err(|e| {
                Error::InvalidWorkspaceConfig {
                    path: config_path,
                    message: format!("Invalid YAML: {e}"),
                }
            })?;
            Ok(true)
        }
    }
}

/// Distinguishes between Yarn Classic (v1) and Yarn Modern (v2+).
///
/// Reads the lockfile format to determine the version:
/// - Yarn Classic uses a custom format starting with `# THIS IS AN AUTOGENERATED FILE`
/// - Yarn Modern (v2+) uses YAML format starting with `__metadata:`
pub(super) fn detect_yarn_version(lockfile_path: &Path) -> Result<PackageManager> {
    let file = fs::File::open(lockfile_path).map_err(|e| Error::Io {
        source: e,
        path: Some(lockfile_path.to_path_buf()),
        operation: "reading yarn.lock".to_string(),
    })?;
    let first_lines = read_first_lines(BufReader::new(file), 5, lockfile_path)?;

    if has_yarn_modern_metadata(&first_lines) {
        Ok(PackageManager::YarnModern)
    } else if has_yarn_classic_header(&first_lines) {
        Ok(PackageManager::YarnClassic)
    } else {
        tracing::warn!(
            "Could not determine Yarn version from lockfile format, defaulting to Classic"
        );
        Ok(PackageManager::YarnClassic)
    }
}

pub(super) fn read_first_lines<R: BufRead>(
    reader: R,
    limit: usize,
    lockfile_path: &Path,
) -> Result<Vec<String>> {
    reader
        .lines()
        .take(limit)
        .collect::<std::io::Result<Vec<_>>>()
        .map_err(|source| Error::Io {
            source,
            path: Some(lockfile_path.to_path_buf()),
            operation: "reading yarn.lock".to_string(),
        })
}

fn has_yarn_modern_metadata(lines: &[String]) -> bool {
    lines.iter().any(|line| line.contains("__metadata:"))
}

fn has_yarn_classic_header(lines: &[String]) -> bool {
    lines.iter().any(|line| {
        line.contains("# yarn lockfile v1") || line.contains("# THIS IS AN AUTOGENERATED FILE")
    })
}
