use super::*;
use tempfile::tempdir;

#[test]
fn test_ignore_file_new() {
    let file = IgnoreFile::new("git");
    assert_eq!(file.tool(), "git");
    assert!(file.patterns_list().is_empty());
    assert_eq!(file.output_filename(), ".gitignore");
}

#[test]
fn test_ignore_file_builder() {
    let file = IgnoreFile::new("docker")
        .pattern("node_modules/")
        .pattern(".env")
        .filename(".mydockerignore")
        .header("My header");

    assert_eq!(file.tool(), "docker");
    assert_eq!(file.patterns_list(), &["node_modules/", ".env"]);
    assert_eq!(file.output_filename(), ".mydockerignore");
}

#[test]
fn test_ignore_file_patterns() {
    let file = IgnoreFile::new("git").patterns(["a", "b", "c"]);
    assert_eq!(file.patterns_list(), &["a", "b", "c"]);
}

#[test]
fn test_ignore_file_generate_no_header() {
    let file = IgnoreFile::new("git")
        .pattern("node_modules/")
        .pattern(".env");

    let content = file.generate();
    assert_eq!(content, "node_modules/\n.env\n");
}

#[test]
fn test_ignore_file_generate_with_header() {
    let file = IgnoreFile::new("git")
        .pattern("node_modules/")
        .header("Generated by my-tool\nDo not edit");

    let content = file.generate();
    assert!(content.starts_with("# Generated by my-tool\n# Do not edit\n\n"));
    assert!(content.contains("node_modules/"));
}

#[test]
fn test_output_filename_default() {
    assert_eq!(IgnoreFile::new("git").output_filename(), ".gitignore");
    assert_eq!(IgnoreFile::new("docker").output_filename(), ".dockerignore");
    assert_eq!(IgnoreFile::new("npm").output_filename(), ".npmignore");
}

#[test]
fn test_output_filename_custom() {
    let file = IgnoreFile::new("git").filename(".my-gitignore");
    assert_eq!(file.output_filename(), ".my-gitignore");
}

#[test]
fn test_validate_tool_name_valid() {
    assert!(validate_tool_name("git").is_ok());
    assert!(validate_tool_name("docker").is_ok());
    assert!(validate_tool_name("my-custom-tool").is_ok());
    assert!(validate_tool_name("tool_with_underscore").is_ok());
}

#[test]
fn test_validate_tool_name_invalid() {
    assert!(validate_tool_name("").is_err());
    assert!(validate_tool_name("../etc").is_err());
    assert!(validate_tool_name("foo/bar").is_err());
    assert!(validate_tool_name("foo\\bar").is_err());
    assert!(validate_tool_name("..").is_err());
    assert!(validate_tool_name("foo..bar").is_err());
}

#[test]
fn test_file_status_display() {
    assert_eq!(FileStatus::Created.to_string(), "Created");
    assert_eq!(FileStatus::Updated.to_string(), "Updated");
    assert_eq!(FileStatus::Unchanged.to_string(), "Unchanged");
    assert_eq!(FileStatus::WouldCreate.to_string(), "Would create");
    assert_eq!(FileStatus::WouldUpdate.to_string(), "Would update");
}

#[test]
fn test_ignore_file_clone() {
    let file = IgnoreFile::new("git")
        .pattern("node_modules/")
        .header("Test");
    let cloned = file.clone();
    assert_eq!(file, cloned);
}

#[test]
fn test_ignore_file_debug() {
    let file = IgnoreFile::new("git");
    let debug_str = format!("{file:?}");
    assert!(debug_str.contains("IgnoreFile"));
    assert!(debug_str.contains("git"));
}

#[test]
fn test_ignore_file_equality() {
    let file1 = IgnoreFile::new("git").pattern("*.log");
    let file2 = IgnoreFile::new("git").pattern("*.log");
    let file3 = IgnoreFile::new("docker").pattern("*.log");

    assert_eq!(file1, file2);
    assert_ne!(file1, file3);
}

#[test]
fn test_ignore_file_filename_opt_some() {
    let file = IgnoreFile::new("git").filename_opt(Some(".custom-ignore"));
    assert_eq!(file.output_filename(), ".custom-ignore");
}

#[test]
fn test_ignore_file_filename_opt_none() {
    let file: IgnoreFile = IgnoreFile::new("git").filename_opt(None::<String>);
    assert_eq!(file.output_filename(), ".gitignore");
}

#[test]
fn test_ignore_files_builder_default() {
    let builder = IgnoreFiles::builder();
    let debug_str = format!("{builder:?}");
    assert!(debug_str.contains("IgnoreFilesBuilder"));
}

#[test]
fn test_validate_filename_valid() {
    assert!(validate_filename(".gitignore").is_ok());
    assert!(validate_filename(".my-custom-ignore").is_ok());
}

#[test]
fn test_validate_filename_invalid() {
    assert!(validate_filename("path/to/file").is_err());
    assert!(validate_filename("..\\file").is_err());
    assert!(validate_filename("file..test").is_err());
}

#[test]
fn test_sync_result_debug() {
    let result = SyncResult {
        files: vec![FileResult {
            filename: ".gitignore".to_string(),
            status: FileStatus::Created,
            pattern_count: 5,
        }],
    };
    let debug_str = format!("{result:?}");
    assert!(debug_str.contains("SyncResult"));
    assert!(debug_str.contains("gitignore"));
}

#[test]
fn test_file_result_debug() {
    let result = FileResult {
        filename: ".gitignore".to_string(),
        status: FileStatus::Updated,
        pattern_count: 3,
    };
    let debug_str = format!("{result:?}");
    assert!(debug_str.contains("FileResult"));
    assert!(debug_str.contains("Updated"));
}

#[test]
fn test_file_status_eq() {
    assert_eq!(FileStatus::Created, FileStatus::Created);
    assert_eq!(FileStatus::WouldCreate, FileStatus::WouldCreate);
    assert_ne!(FileStatus::Created, FileStatus::Updated);
}

#[test]
fn test_file_status_clone() {
    let status = FileStatus::WouldUpdate;
    let cloned = status;
    assert_eq!(status, cloned);
}

#[test]
fn test_error_display() {
    let err = Error::InvalidToolName {
        name: "foo/bar".to_string(),
        reason: "cannot contain path separators".to_string(),
    };
    let display = format!("{err}");
    assert!(display.contains("foo/bar"));
    assert!(display.contains("path separators"));
}

#[test]
fn test_error_not_in_git_repo_display() {
    let err = Error::NotInGitRepo;
    let display = format!("{err}");
    assert!(display.contains("Git repository"));
}

#[test]
fn test_error_bare_repository_display() {
    let err = Error::BareRepository;
    let display = format!("{err}");
    assert!(display.contains("bare Git repository"));
}

#[test]
fn test_error_outside_git_repo_display() {
    let err = Error::OutsideGitRepo;
    let display = format!("{err}");
    assert!(display.contains("within the Git repository"));
}

#[test]
fn test_ignore_file_generate_empty() {
    let file = IgnoreFile::new("git");
    let content = file.generate();
    assert_eq!(content, "\n");
}

#[test]
fn test_ignore_files_builder_files() {
    let files = vec![
        IgnoreFile::new("git").pattern("*.log"),
        IgnoreFile::new("docker").pattern("target/"),
    ];
    let _builder = IgnoreFiles::builder().files(files);
}

#[test]
fn test_managed_section_create_update_and_remove() {
    let temp = tempdir().expect("tempdir");

    let result = IgnoreFiles::builder()
        .directory(temp.path())
        .section(
            IgnoreSection::new("cuenv vcs")
                .pattern(".cuenv/vcs/cache/")
                .pattern(".cuenv/vcs/lib/"),
        )
        .generate()
        .expect("create section");
    assert_eq!(result.files[0].status, FileStatus::Created);
    let content = std::fs::read_to_string(temp.path().join(".gitignore")).expect("gitignore");
    assert_eq!(
        content,
        "# BEGIN cuenv vcs\n.cuenv/vcs/cache/\n.cuenv/vcs/lib/\n# END cuenv vcs\n"
    );

    let result = IgnoreFiles::builder()
        .directory(temp.path())
        .section(IgnoreSection::new("cuenv vcs").pattern(".cuenv/vcs/cache/"))
        .generate()
        .expect("update section");
    assert_eq!(result.files[0].status, FileStatus::Updated);
    let content = std::fs::read_to_string(temp.path().join(".gitignore")).expect("gitignore");
    assert!(content.contains(".cuenv/vcs/cache/"));
    assert!(!content.contains(".cuenv/vcs/lib/"));

    let result = IgnoreFiles::builder()
        .directory(temp.path())
        .section(IgnoreSection::new("cuenv vcs"))
        .generate()
        .expect("remove section");
    assert_eq!(result.files[0].status, FileStatus::Updated);
    let content = std::fs::read_to_string(temp.path().join(".gitignore")).expect("gitignore");
    assert!(!content.contains("# BEGIN cuenv vcs"));
}

#[test]
fn test_managed_section_dry_run_and_empty_absent_file() {
    let temp = tempdir().expect("tempdir");

    let result = IgnoreFiles::builder()
        .directory(temp.path())
        .dry_run(true)
        .section(IgnoreSection::new("cuenv vcs").pattern(".cuenv/vcs/cache/"))
        .generate()
        .expect("dry run");
    assert_eq!(result.files[0].status, FileStatus::WouldCreate);
    assert!(!temp.path().join(".gitignore").exists());

    let result = IgnoreFiles::builder()
        .directory(temp.path())
        .section(IgnoreSection::new("cuenv vcs"))
        .generate()
        .expect("empty section");
    assert_eq!(result.files[0].status, FileStatus::Unchanged);
    assert!(!temp.path().join(".gitignore").exists());
}

#[test]
fn test_managed_section_dangling_ignore_file_errors() {
    let temp = tempdir().expect("tempdir");
    #[cfg(unix)]
    std::os::unix::fs::symlink("missing-target", temp.path().join(".gitignore"))
        .expect("dangling symlink");
    #[cfg(windows)]
    std::os::windows::fs::symlink_file("missing-target", temp.path().join(".gitignore"))
        .expect("dangling symlink");

    let err = IgnoreFiles::builder()
        .directory(temp.path())
        .section(IgnoreSection::new("cuenv vcs"))
        .generate()
        .expect_err("dangling ignore file should fail");
    assert!(matches!(err, Error::Io(_)));
}

#[test]
fn test_full_file_generation_preserves_managed_sections() {
    let temp = tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join(".gitignore"),
        "target/\n\n# BEGIN cuenv vcs\n.cuenv/vcs/cache/\n# END cuenv vcs\n",
    )
    .expect("seed gitignore");

    IgnoreFiles::builder()
        .directory(temp.path())
        .file(IgnoreFile::new("git").pattern("dist/"))
        .generate()
        .expect("generate file");

    let content = std::fs::read_to_string(temp.path().join(".gitignore")).expect("gitignore");
    assert!(content.contains("dist/"));
    assert!(!content.contains("target/"));
    assert!(content.contains("# BEGIN cuenv vcs\n.cuenv/vcs/cache/\n# END cuenv vcs"));
}

#[test]
fn test_managed_sections_reject_malformed_blocks() {
    let temp = tempdir().expect("tempdir");
    std::fs::write(
        temp.path().join(".gitignore"),
        "# BEGIN cuenv vcs\n.cuenv/vcs/cache/\n",
    )
    .expect("seed gitignore");

    let err = IgnoreFiles::builder()
        .directory(temp.path())
        .section(IgnoreSection::new("cuenv vcs").pattern(".cuenv/vcs/lib/"))
        .generate()
        .expect_err("malformed section should fail");
    assert!(err.to_string().contains("missing end marker"));
}
