//! CUE types generated from a provider's schema.
//!
//! `cuenv infrastructure provider add` and `cuenv sync infrastructure` render
//! the schema cuenv reads over gRPC as CUE packages under `cue.mod/gen`, one
//! for the provider block and one per managed resource type:
//!
//! ```text
//! cue.mod/gen/registry.terraform.io/hashicorp/random/provider.cue
//! cue.mod/gen/registry.terraform.io/hashicorp/random/resources/random_pet/resource.cue
//! ```
//!
//! The provider package defines `#Provider` (source, version and schema
//! digest bound to the types) and `#Configuration`; each resource package
//! defines `#Resource` (bound to its type) and `#Configuration`. Field names
//! are Terraform's attribute names, which is what the engine decodes.
//!
//! The [schema digest](schema_digest) covers what the generated
//! `#Configuration` definitions encode, so the engine can tell at plan time
//! whether the types in use were generated from the provider it launched.
//!
//! See `docs/design/specs/2026-10-03-infrastructure-provider-types.md`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde_json::json;
use sha2::{Digest, Sha256};

use crate::cancellation::Cancellation;
use crate::error::{InfrastructureError, Result};
use crate::plugin::{LaunchOptions, ProviderClient, isolated_withheld_names};
use crate::registry::ProviderSource;
use crate::schema::{
    Attribute, Block, Documentation, NestedAttributes, NestedBlock, Nesting, Presence,
    ProviderSchema,
};
use crate::type_system::Type;

/// First line of every generated file. `cuenv sync infrastructure` only
/// replaces a provider directory whose `provider.cue` starts with it.
pub const GENERATED_HEADER: &str = "// Code generated by cuenv. DO NOT EDIT.";

/// File holding the provider package, inside the provider directory.
pub const PROVIDER_FILE_NAME: &str = "provider.cue";

/// Directory holding one package per resource type, inside the provider
/// directory.
pub const RESOURCES_DIRECTORY_NAME: &str = "resources";

/// File holding a resource package, inside its directory.
pub const RESOURCE_FILE_NAME: &str = "resource.cue";

/// Prefix of every schema digest.
pub const SCHEMA_DIGEST_PREFIX: &str = "sha256:";

/// Predeclared identifiers, and the `list` import, that generated types
/// refer to. A field with one of these names is written with a quoted label:
/// an identifier label would shadow the predeclared one for every reference
/// in the same struct (`length!: number` next to a `number` attribute), but
/// a quoted label cannot be referenced.
const REFERENCED_IDENTIFIERS: &[&str] =
    &["bool", "number", "string", "int", "float", "bytes", "list"];

/// CUE keywords, which are quoted when used as labels.
const KEYWORDS: &[&str] = &[
    "package", "import", "for", "in", "if", "let", "true", "false", "null", "func",
];

/// A provider release the types describe.
#[derive(Debug, Clone, Copy)]
pub struct ProviderRelease<'release> {
    /// Provider source address.
    pub source: &'release ProviderSource,
    /// Exact provider version.
    pub version: &'release str,
}

/// The generated packages of one provider.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedTypes {
    /// Import path of the provider package, for example
    /// `registry.terraform.io/hashicorp/random`.
    pub import_path: String,
    /// Package name of the provider package.
    pub package_name: String,
    /// Directory of the provider package, relative to the CUE module root.
    pub directory: PathBuf,
    /// File contents keyed by path relative to [`Self::directory`].
    pub files: BTreeMap<PathBuf, String>,
    /// Digest of the schema the types were generated from.
    pub schema_digest: String,
    /// Managed resource types, sorted.
    pub resource_types: Vec<String>,
}

impl GeneratedTypes {
    /// The `import` line for the provider package.
    #[must_use]
    pub fn provider_import(&self) -> String {
        import_line(&self.import_path, &self.package_name)
    }

    /// The `import` line for one resource type's package.
    #[must_use]
    pub fn resource_import(&self, resource_type: &str) -> String {
        import_line(
            &format!(
                "{}/{RESOURCES_DIRECTORY_NAME}/{resource_type}",
                self.import_path
            ),
            resource_type,
        )
    }
}

/// An unaliased import: the package's identifier is the last path element,
/// or the qualifier when the package is named differently.
fn import_line(path: &str, package_name: &str) -> String {
    let last = path.rsplit('/').next().unwrap_or(path);
    if last == package_name {
        format!("\"{path}\"")
    } else {
        format!("\"{path}:{package_name}\"")
    }
}

/// Import path of a provider's generated package:
/// `<hostname>/<namespace>/<type>`.
///
/// # Errors
///
/// Returns [`InfrastructureError::Configuration`] for a source whose hostname
/// has a port: `:` would start a CUE package qualifier.
pub fn import_path(source: &ProviderSource) -> Result<String> {
    source.validate()?;
    if source.hostname.contains(':') {
        return Err(InfrastructureError::configuration(format!(
            "cannot generate CUE types for {source}: a registry hostname with a port cannot be part of a CUE import path"
        )));
    }
    Ok(format!(
        "{}/{}/{}",
        source.hostname, source.namespace, source.type_name
    ))
}

/// Directory of a provider's generated package, relative to the CUE module
/// root: `cue.mod/gen/<import path>`.
///
/// # Errors
///
/// As [`import_path`].
pub fn directory(source: &ProviderSource) -> Result<PathBuf> {
    let mut directory = Path::new("cue.mod").join("gen");
    for component in import_path(source)?.split('/') {
        directory.push(component);
    }
    Ok(directory)
}

/// Package name of a provider's generated package: the provider type with
/// `-` replaced by `_` and `_provider` appended (`random_provider`).
///
/// The suffix keeps the package's identifier apart from the local provider
/// name: in `providers: random: random.#Provider` the field `random` would
/// shadow an import named `random`.
#[must_use]
pub fn provider_package_name(type_name: &str) -> String {
    let mut name: String = type_name
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect();
    if name.starts_with(|character: char| !character.is_ascii_alphabetic()) {
        name.insert_str(0, "provider_");
    }
    name.push_str("_provider");
    name
}

/// Launch a provider executable with an isolated environment and read its
/// schema. Provider warnings are returned; error diagnostics fail.
///
/// # Errors
///
/// Returns an error when the provider cannot be launched, the schema cannot
/// be read or decoded, or the provider reports errors.
pub async fn load_schema(
    binary: &Path,
    cancellation: &Cancellation,
) -> Result<(ProviderSchema, Vec<String>)> {
    let ambient: Vec<std::ffi::OsString> = std::env::vars_os().map(|(name, _)| name).collect();
    let withheld = isolated_withheld_names(ambient, &[]);
    let client = ProviderClient::launch(&LaunchOptions {
        binary,
        withheld_environment_variables: &withheld,
        provider_environment_variables: &BTreeMap::new(),
        cancellation,
    })
    .await?;
    let result = client.schema().await;
    client.shutdown().await;
    let (schema, diagnostics) = result?;
    let mut warnings = Vec::new();
    crate::engine::check_diagnostics("load provider schema", &diagnostics, &mut warnings)?;
    Ok((schema, warnings))
}

/// Digest of what the generated `#Configuration` definitions encode.
///
/// `sha256:` and the hex SHA-256 of a canonical JSON document holding, for
/// the provider block and every managed resource, each attribute's type,
/// nesting and flags and each nested block's nesting and item bounds.
/// Descriptions, deprecation messages and schema versions are left out.
#[must_use]
pub fn schema_digest(schema: &ProviderSchema) -> String {
    let resources: BTreeMap<&String, serde_json::Value> = schema
        .resources
        .iter()
        .map(|(name, resource)| (name, block_document(&resource.block)))
        .collect();
    let document = json!({
        "format": 1,
        "provider": block_document(&schema.provider.block),
        "resources": resources,
    });
    let mut hasher = Sha256::new();
    hasher.update(document.to_string().as_bytes());
    format!("{SCHEMA_DIGEST_PREFIX}{}", hex::encode(hasher.finalize()))
}

fn block_document(block: &Block) -> serde_json::Value {
    let attributes: BTreeMap<&String, serde_json::Value> = block
        .attributes
        .iter()
        .map(|(name, attribute)| (name, attribute_document(attribute)))
        .collect();
    let blocks: BTreeMap<&String, serde_json::Value> = block
        .blocks
        .iter()
        .map(|(name, nested)| {
            (
                name,
                json!({
                    "nesting": nesting_name(nested.nesting),
                    "minimum_items": nested.minimum_items,
                    "maximum_items": nested.maximum_items,
                    "block": block_document(&nested.block),
                }),
            )
        })
        .collect();
    json!({"attributes": attributes, "blocks": blocks})
}

fn attribute_document(attribute: &Attribute) -> serde_json::Value {
    let shape = match &attribute.nested {
        Some(nested) => {
            let attributes: BTreeMap<&String, serde_json::Value> = nested
                .attributes
                .iter()
                .map(|(name, attribute)| (name, attribute_document(attribute)))
                .collect();
            json!({"nesting": nesting_name(nested.nesting), "attributes": attributes})
        }
        None => attribute.value_type.to_json(),
    };
    json!({
        "shape": shape,
        "presence": presence_name(attribute.presence),
        "sensitive": attribute.sensitive,
        "write_only": attribute.write_only,
        "deprecated": attribute.documentation.deprecated,
    })
}

const fn nesting_name(nesting: Nesting) -> &'static str {
    match nesting {
        Nesting::Single => "single",
        Nesting::Group => "group",
        Nesting::List => "list",
        Nesting::Set => "set",
        Nesting::Map => "map",
    }
}

const fn presence_name(presence: Presence) -> &'static str {
    match presence {
        Presence::Required => "required",
        Presence::Optional => "optional",
        Presence::Computed => "computed",
        Presence::OptionalComputed => "optional_computed",
    }
}

/// Render a provider's schema as CUE packages.
///
/// # Errors
///
/// As [`import_path`].
pub fn render(schema: &ProviderSchema, release: ProviderRelease<'_>) -> Result<GeneratedTypes> {
    let import_path = import_path(release.source)?;
    let directory = directory(release.source)?;
    let package_name = provider_package_name(&release.source.type_name);
    let schema_digest = schema_digest(schema);
    let mut files = BTreeMap::new();

    let description = format!("{} {}", release.source, release.version);
    let mut provider = Package::new(&description, "the provider's configuration block");
    provider.line(
        0,
        "// #Provider declares the provider at exactly the version and schema",
    );
    provider.line(0, "// these types were generated from.");
    provider.line(0, "#Provider: {");
    provider.field(1, "source", &cue_string(&release.source.to_string()));
    provider.field(1, "version", &cue_string(release.version));
    provider.field(1, "schemaDigest", &cue_string(&schema_digest));
    provider.field(1, "configuration", "#Configuration");
    provider.line(0, "}");
    provider.blank();
    provider.configuration(&schema.provider.block);
    files.insert(
        PathBuf::from(PROVIDER_FILE_NAME),
        provider.finish(&package_name),
    );

    let mut resource_types: Vec<String> = schema.resources.keys().cloned().collect();
    resource_types.sort();
    for resource_type in &resource_types {
        let Some(resource) = schema.resources.get(resource_type) else {
            continue;
        };
        let mut package = Package::new(&description, &format!("the {resource_type} resource"));
        package.line(
            0,
            &format!("// #Resource declares a managed resource of type {resource_type}."),
        );
        let documentation = documentation_lines(&resource.block.documentation, &[]);
        if !documentation.is_empty() {
            package.line(0, "//");
            package.comment_lines(0, &documentation);
        }
        package.line(0, "#Resource: {");
        package.field(1, "type", &cue_string(resource_type));
        package.field(1, "configuration", "#Configuration");
        package.line(1, "...");
        package.line(0, "}");
        package.blank();
        package.configuration(&resource.block);
        files.insert(
            Path::new(RESOURCES_DIRECTORY_NAME)
                .join(resource_type)
                .join(RESOURCE_FILE_NAME),
            package.finish(resource_type),
        );
    }

    Ok(GeneratedTypes {
        import_path,
        package_name,
        directory,
        files,
        schema_digest,
        resource_types,
    })
}

/// One generated file being written.
struct Package {
    header: String,
    body: String,
    uses_list: bool,
}

impl Package {
    fn new(release: &str, subject: &str) -> Self {
        let header = [
            GENERATED_HEADER.to_string(),
            "//".to_string(),
            format!("// Types for {subject} of {release},"),
            "// generated from the provider's schema. Regenerate them with".to_string(),
            "// `cuenv sync infrastructure`.".to_string(),
        ]
        .join("\n");
        Self {
            header,
            body: String::new(),
            uses_list: false,
        }
    }

    fn finish(self, package_name: &str) -> String {
        let mut output = self.header;
        let _ = write!(output, "\n\npackage {package_name}\n\n");
        if self.uses_list {
            output.push_str("import \"list\"\n\n");
        }
        output.push_str(self.body.trim_end());
        output.push('\n');
        output
    }

    fn line(&mut self, depth: usize, text: &str) {
        for _ in 0..depth {
            self.body.push('\t');
        }
        self.body.push_str(text);
        self.body.push('\n');
    }

    fn blank(&mut self) {
        self.body.push('\n');
    }

    fn field(&mut self, depth: usize, label: &str, value: &str) {
        self.line(depth, &format!("{label}: {value}"));
    }

    fn comment_lines(&mut self, depth: usize, lines: &[String]) {
        for line in lines {
            if line.is_empty() {
                self.line(depth, "//");
            } else {
                self.line(depth, &format!("// {line}"));
            }
        }
    }

    fn configuration(&mut self, block: &Block) {
        let value = self.block_struct(block, 0);
        self.line(0, &format!("#Configuration: {value}"));
    }

    /// The struct a block's configuration is written as, opening at the
    /// current position and closing at `depth`.
    fn block_struct(&mut self, block: &Block, depth: usize) -> String {
        let mut fields = Fields::default();
        for (name, attribute) in &block.attributes {
            if let Some(field) = self.attribute_field(name, attribute, depth + 1) {
                fields.0.insert(name.clone(), field);
            }
        }
        for (name, nested) in &block.blocks {
            let field = self.nested_block_field(name, nested, depth + 1);
            fields.0.insert(name.clone(), field);
        }
        fields.render(depth)
    }

    fn attribute_field(
        &mut self,
        name: &str,
        attribute: &Attribute,
        depth: usize,
    ) -> Option<Field> {
        if attribute.write_only || attribute.presence == Presence::Computed {
            return None;
        }
        let mut notes = Vec::new();
        if attribute.presence == Presence::OptionalComputed {
            notes.push("The provider chooses a value when this is not set.");
        }
        if attribute.sensitive {
            notes.push("Sensitive: plans show it as (sensitive).");
        }
        let value = match &attribute.nested {
            Some(nested) => self.nested_attributes(nested, depth),
            None => type_expression(&attribute.value_type, depth),
        };
        Some(Field {
            comments: documentation_lines(&attribute.documentation, &notes),
            label: label(name),
            marker: if attribute.presence == Presence::Required {
                '!'
            } else {
                '?'
            },
            value,
        })
    }

    fn nested_attributes(&mut self, nested: &NestedAttributes, depth: usize) -> String {
        let mut fields = Fields::default();
        for (name, attribute) in &nested.attributes {
            if let Some(field) = self.attribute_field(name, attribute, depth + 1) {
                fields.0.insert(name.clone(), field);
            }
        }
        let object = fields.render(depth);
        match nested.nesting {
            Nesting::Single | Nesting::Group => object,
            Nesting::List | Nesting::Set => format!("[...{object}]"),
            Nesting::Map => format!("{{[string]: {object}}}"),
        }
    }

    fn nested_block_field(&mut self, name: &str, nested: &NestedBlock, depth: usize) -> Field {
        let object = self.block_struct(&nested.block, depth);
        let required = nested.minimum_items > 0 && nested.nesting != Nesting::Group;
        let value = match nested.nesting {
            Nesting::Single | Nesting::Group => object,
            Nesting::Map => format!("{{[string]: {object}}}"),
            Nesting::List | Nesting::Set => {
                let mut value = format!("[...{object}]");
                if nested.minimum_items > 0 {
                    let _ = write!(value, " & list.MinItems({})", nested.minimum_items);
                    self.uses_list = true;
                }
                if nested.maximum_items > 0 {
                    let _ = write!(value, " & list.MaxItems({})", nested.maximum_items);
                    self.uses_list = true;
                }
                value
            }
        };
        Field {
            comments: documentation_lines(&nested.block.documentation, &[]),
            label: label(name),
            marker: if required { '!' } else { '?' },
            value,
        }
    }
}

/// One field of a generated struct.
struct Field {
    comments: Vec<String>,
    label: String,
    marker: char,
    value: String,
}

/// Fields of a struct, sorted by name.
#[derive(Default)]
struct Fields(BTreeMap<String, Field>);

impl Fields {
    /// Render as a struct literal whose closing brace sits at `depth`.
    fn render(&self, depth: usize) -> String {
        if self.0.is_empty() {
            return "{}".to_string();
        }
        let indentation = "\t".repeat(depth + 1);
        let mut output = String::from("{\n");
        for field in self.0.values() {
            for comment in &field.comments {
                if comment.is_empty() {
                    let _ = writeln!(output, "{indentation}//");
                } else {
                    let _ = writeln!(output, "{indentation}// {comment}");
                }
            }
            let _ = writeln!(
                output,
                "{indentation}{}{}: {}",
                field.label, field.marker, field.value
            );
        }
        output.push_str(&"\t".repeat(depth));
        output.push('}');
        output
    }
}

/// The CUE expression for a cty type, for a value at `depth`.
fn type_expression(value_type: &Type, depth: usize) -> String {
    match value_type {
        Type::Boolean => "bool".to_string(),
        Type::Number => "number".to_string(),
        Type::String => "string".to_string(),
        Type::Dynamic => "_".to_string(),
        Type::List(element) | Type::Set(element) => {
            format!("[...{}]", type_expression(element, depth))
        }
        Type::Map(element) => format!("{{[string]: {}}}", type_expression(element, depth)),
        Type::Tuple(elements) => format!(
            "[{}]",
            elements
                .iter()
                .map(|element| type_expression(element, depth))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        // Terraform requires every attribute of an object type.
        Type::Object(attributes) => {
            let mut fields = Fields::default();
            for (name, attribute_type) in attributes {
                fields.0.insert(
                    name.clone(),
                    Field {
                        comments: Vec::new(),
                        label: label(name),
                        marker: '!',
                        value: type_expression(attribute_type, depth + 1),
                    },
                );
            }
            fields.render(depth)
        }
    }
}

/// Comment lines for a documented attribute or block, followed by `notes`.
fn documentation_lines(documentation: &Documentation, notes: &[&str]) -> Vec<String> {
    let mut lines: Vec<String> = comment_text(&documentation.description);
    if documentation.deprecated {
        let message = comment_text(&documentation.deprecation_message);
        if !lines.is_empty() {
            lines.push(String::new());
        }
        match message.split_first() {
            Some((first, rest)) => {
                lines.push(format!("Deprecated: {first}"));
                lines.extend(rest.iter().cloned());
            }
            None => lines.push("Deprecated.".to_string()),
        }
    }
    for note in notes {
        lines.push((*note).to_string());
    }
    lines
}

/// Provider text as comment lines: control characters removed, trailing
/// whitespace and surrounding blank lines dropped.
fn comment_text(text: &str) -> Vec<String> {
    let cleaned =
        crate::error::strip_control_characters_except_newlines(&text.replace("\r\n", "\n"));
    let lines: Vec<String> = cleaned
        .lines()
        .map(|line| line.trim_end().to_string())
        .collect();
    let start = lines.iter().position(|line| !line.is_empty());
    let end = lines.iter().rposition(|line| !line.is_empty());
    match (start, end) {
        (Some(start), Some(end)) => lines
            .get(start..=end)
            .map(<[String]>::to_vec)
            .unwrap_or_default(),
        _ => Vec::new(),
    }
}

/// A field label: the name itself when it is a plain identifier, otherwise
/// a quoted string.
fn label(name: &str) -> String {
    let plain = name.starts_with(|character: char| character.is_ascii_alphabetic())
        && name
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_')
        && !KEYWORDS.contains(&name)
        && !REFERENCED_IDENTIFIERS.contains(&name);
    if plain {
        name.to_string()
    } else {
        cue_string(name)
    }
}

/// A CUE string literal. JSON string escapes are valid CUE.
fn cue_string(value: &str) -> String {
    serde_json::Value::String(value.to_string()).to_string()
}

#[cfg(test)]
mod tests;
