package examples

import (
	"github.com/cuenv/cuenv/schema"

	// Generated by `cuenv infrastructure provider add hashicorp/random@3.9.1`
	// into this module's cue.mod/gen and pinned in its cuenv.lock.
	"registry.terraform.io/hashicorp/random:random_provider"
	"registry.terraform.io/hashicorp/random/resources/random_integer"
	"registry.terraform.io/hashicorp/random/resources/random_password"
	"registry.terraform.io/hashicorp/random/resources/random_pet"
)

schema.#Project

name: "infrastructure-typed"

// The typed version of examples/infrastructure-random: every `configuration`
// is checked by CUE against types generated from the provider's own schema,
// so a misspelled argument, a wrong type or a missing required argument fails
// evaluation with its file position, before any provider starts.
//
//   sqld --http-listen-addr 127.0.0.1:8080   # or point url at libsql://...
//   cuenv i plan  -p examples/infrastructure-typed --package examples
//   cuenv i apply -p examples/infrastructure-typed --package examples
//
// `random_provider.#Provider` sets `source`, `version` and `schemaDigest`;
// `cuenv i plan` refuses a provider binary whose schema is not the one the
// types were generated from. Regenerate with `cuenv sync infrastructure`.
infrastructure: {
	state: turso: url: "http://127.0.0.1:8080"

	providers: random: random_provider.#Provider

	resources: {
		pet: random_pet.#Resource & {
			configuration: {
				length:    2
				separator: "-"
			}
		}
		database_password: random_password.#Resource & {
			configuration: {
				length:  24
				special: false
			}
		}
		port: random_integer.#Resource & {
			dependsOn: ["pet"]
			configuration: {
				min: 8000
				max: 8999
				keepers: pet: "rotate-with-pet"
			}
		}
	}
}
