use super::*;
use crate::schema::{ProviderCapabilities, Schema};
use std::collections::HashMap;

fn attribute(value_type: Type, presence: Presence) -> Attribute {
    Attribute {
        value_type,
        nested: None,
        presence,
        sensitive: false,
        write_only: false,
        documentation: Documentation::default(),
    }
}

fn described(mut attribute: Attribute, description: &str) -> Attribute {
    attribute.documentation.description = description.to_string();
    attribute
}

fn pet_block() -> Block {
    let mut block = Block::default();
    block
        .attributes
        .insert("id".into(), attribute(Type::String, Presence::Computed));
    block.attributes.insert(
        "length".into(),
        described(
            attribute(Type::Number, Presence::Optional),
            "The length (in words) of the pet name.",
        ),
    );
    block.attributes.insert(
        "keepers".into(),
        attribute(Type::Map(Box::new(Type::String)), Presence::Optional),
    );
    block.attributes.insert(
        "separator".into(),
        attribute(Type::String, Presence::OptionalComputed),
    );
    let mut token = attribute(Type::String, Presence::Optional);
    token.write_only = true;
    block.attributes.insert("token".into(), token);
    let mut prefix = attribute(Type::String, Presence::Optional);
    prefix.documentation.deprecated = true;
    prefix.documentation.deprecation_message = "Use `separator`.".into();
    block.attributes.insert("prefix".into(), prefix);
    let mut rule = Block::default();
    rule.attributes
        .insert("port".into(), attribute(Type::Number, Presence::Required));
    rule.attributes.insert(
        "for".into(),
        attribute(
            Type::Object(BTreeMap::from([
                ("cidr".to_string(), Type::String),
                (
                    "ports".to_string(),
                    Type::Tuple(vec![Type::Number, Type::Number]),
                ),
            ])),
            Presence::Optional,
        ),
    );
    block.blocks.insert(
        "rule".into(),
        NestedBlock {
            block: rule,
            nesting: Nesting::List,
            minimum_items: 1,
            maximum_items: 3,
        },
    );
    block
}

fn provider_schema() -> ProviderSchema {
    let mut provider = Block::default();
    let mut secret = attribute(Type::String, Presence::Required);
    secret.sensitive = true;
    provider.attributes.insert("api_key".into(), secret);
    ProviderSchema {
        provider: Schema {
            version: 0,
            block: provider,
        },
        resources: HashMap::from([
            (
                "example_pet".to_string(),
                Schema {
                    version: 1,
                    block: pet_block(),
                },
            ),
            (
                "example_empty".to_string(),
                Schema {
                    version: 0,
                    block: Block::default(),
                },
            ),
        ]),
        capabilities: ProviderCapabilities::default(),
    }
}

fn source() -> ProviderSource {
    ProviderSource::parse("acme/example-cloud").unwrap()
}

fn generated() -> GeneratedTypes {
    let source = source();
    render(
        &provider_schema(),
        ProviderRelease {
            source: &source,
            version: "1.2.3",
        },
    )
    .unwrap()
}

#[test]
fn provider_package_binds_source_version_and_digest() {
    let types = generated();
    assert_eq!(
        types.import_path,
        "registry.terraform.io/acme/example-cloud"
    );
    assert_eq!(types.package_name, "example_cloud_provider");
    assert_eq!(
        types.directory,
        Path::new("cue.mod/gen/registry.terraform.io/acme/example-cloud")
    );
    let provider = types.files.get(Path::new("provider.cue")).unwrap();
    let expected = format!(
        r#"// Code generated by cuenv. DO NOT EDIT.
//
// Types for the provider's configuration block of registry.terraform.io/acme/example-cloud 1.2.3,
// generated from the provider's schema. Regenerate them with
// `cuenv sync infrastructure`.

package example_cloud_provider

// #Provider declares the provider at exactly the version and schema
// these types were generated from.
#Provider: {{
	source: "registry.terraform.io/acme/example-cloud"
	version: "1.2.3"
	schemaDigest: "{digest}"
	configuration: #Configuration
}}

#Configuration: {{
	// Sensitive: plans show it as (sensitive).
	api_key!: string
}}
"#,
        digest = types.schema_digest
    );
    assert_eq!(provider, &expected);
}

#[test]
fn resource_package_follows_the_field_rules() {
    let types = generated();
    assert_eq!(types.resource_types, ["example_empty", "example_pet"]);
    let pet = types
        .files
        .get(Path::new("resources/example_pet/resource.cue"))
        .unwrap();
    let expected = r#"// Code generated by cuenv. DO NOT EDIT.
//
// Types for the example_pet resource of registry.terraform.io/acme/example-cloud 1.2.3,
// generated from the provider's schema. Regenerate them with
// `cuenv sync infrastructure`.

package example_pet

import "list"

// #Resource declares a managed resource of type example_pet.
#Resource: {
	type: "example_pet"
	configuration: #Configuration
	...
}

#Configuration: {
	keepers?: {[string]: string}
	// The length (in words) of the pet name.
	length?: number
	// Deprecated: Use `separator`.
	prefix?: string
	rule!: [...{
		"for"?: {
			cidr!: string
			ports!: [number, number]
		}
		port!: number
	}] & list.MinItems(1) & list.MaxItems(3)
	// The provider chooses a value when this is not set.
	separator?: string
}
"#;
    assert_eq!(pet, expected);
    let empty = types
        .files
        .get(Path::new("resources/example_empty/resource.cue"))
        .unwrap();
    assert!(empty.ends_with("#Configuration: {}\n"), "{empty}");
    assert!(!empty.contains("import"), "{empty}");
}

#[test]
fn import_lines_qualify_provider_packages() {
    let types = generated();
    assert_eq!(
        types.provider_import(),
        r#""registry.terraform.io/acme/example-cloud:example_cloud_provider""#
    );
    assert_eq!(
        types.resource_import("example_pet"),
        r#""registry.terraform.io/acme/example-cloud/resources/example_pet""#
    );
    let random = ProviderSource::parse("hashicorp/random").unwrap();
    let types = render(
        &provider_schema(),
        ProviderRelease {
            source: &random,
            version: "3.9.1",
        },
    )
    .unwrap();
    assert_eq!(
        types.provider_import(),
        r#""registry.terraform.io/hashicorp/random:random_provider""#
    );
}

#[test]
fn provider_package_names_are_identifiers_apart_from_local_names() {
    assert_eq!(provider_package_name("random"), "random_provider");
    assert_eq!(provider_package_name("google-beta"), "google_beta_provider");
    assert_eq!(provider_package_name("null"), "null_provider");
    assert_eq!(
        provider_package_name("1password"),
        "provider_1password_provider"
    );
}

#[test]
fn a_hostname_with_a_port_cannot_be_an_import_path() {
    let source = ProviderSource::parse("localhost:8443/acme/example").unwrap();
    let error = import_path(&source).unwrap_err().to_string();
    assert!(error.contains("port"), "{error}");
}

#[test]
fn descriptions_do_not_change_the_digest_but_shapes_do() {
    let schema = provider_schema();
    let digest = schema_digest(&schema);
    assert!(digest.starts_with("sha256:"), "{digest}");
    assert_eq!(digest.len(), "sha256:".len() + 64);
    assert_eq!(
        digest,
        schema_digest(&provider_schema()),
        "digest is stable"
    );

    let mut described = provider_schema();
    if let Some(pet) = described.resources.get_mut("example_pet") {
        pet.block.documentation.description = "A pet.".into();
        pet.version = 7;
        if let Some(length) = pet.block.attributes.get_mut("length") {
            length.documentation.description = "Something else.".into();
        }
    }
    assert_eq!(digest, schema_digest(&described));

    let mut required = provider_schema();
    if let Some(length) = required
        .resources
        .get_mut("example_pet")
        .and_then(|pet| pet.block.attributes.get_mut("length"))
    {
        length.presence = Presence::Required;
    }
    assert_ne!(digest, schema_digest(&required));

    let mut fewer = provider_schema();
    fewer.resources.remove("example_empty");
    assert_ne!(digest, schema_digest(&fewer));
}

#[test]
fn provider_text_cannot_escape_a_comment() {
    let documentation = Documentation {
        description: "\n\nFirst line\r\nSecond\u{1b}[31m line\n\n".into(),
        deprecated: true,
        deprecation_message: String::new(),
    };
    assert_eq!(
        documentation_lines(&documentation, &["Note."]),
        ["First line", "Second[31m line", "", "Deprecated.", "Note."]
    );
}

#[test]
fn labels_that_are_not_plain_identifiers_are_quoted() {
    assert_eq!(label("name"), "name");
    assert_eq!(label("if"), "\"if\"");
    assert_eq!(label("_hidden"), "\"_hidden\"");
    assert_eq!(label("9lives"), "\"9lives\"");
    assert_eq!(label("with-dash"), "\"with-dash\"");
    // A `number` field would shadow the predeclared type `number`.
    assert_eq!(label("number"), "\"number\"");
    assert_eq!(label("list"), "\"list\"");
}

#[test]
fn protocol_six_nested_attributes_are_rendered_recursively() {
    let mut block = Block::default();
    let mut nested = BTreeMap::new();
    nested.insert(
        "name".to_string(),
        attribute(Type::String, Presence::Required),
    );
    nested.insert(
        "id".to_string(),
        attribute(Type::String, Presence::Computed),
    );
    block.attributes.insert(
        "tags".into(),
        Attribute {
            nested: Some(NestedAttributes {
                attributes: nested,
                nesting: Nesting::Map,
            }),
            ..attribute(Type::Dynamic, Presence::Optional)
        },
    );
    let mut package = Package::new("x 1.0.0", "a test");
    package.configuration(&block);
    assert_eq!(
        package.body,
        "#Configuration: {\n\ttags?: {[string]: {\n\t\tname!: string\n\t}}\n}\n"
    );
}
